<STMTS> ::= <STMTS> <STMT> | <STMT>
<STMT>  ::= <DEC> | <EXPR> TKTYPE_SMCOLON 

<DEC>   ::= <TIPO> TKTYPE_VAR TKTYPE_ATTRIBUTION <EXPR> TKTYPE_SMCOLON

<EXPR>  ::= <LOGIC_OR>  | <EXPR1>
<LOGIC_OR> ::= <EXPR> TKTYPE_LOGIC_OR <EXPR1>

<EXPR1> ::=  <LOGIC_AND> | <EXPR2>
<LOGIC_AND> ::= <EXPR1> TKTYPE_LOGIC_AND <EXPR2>

<EXPR2>   ::= <CMP_EQ>| <CMP_NEQ> | <EXPR3>
<CMP_EQ>  ::= <EXPR2> TKTYPE_EQUALS   <EXPR3>
<CMP_NEQ> ::= <EXPR2> TKTYPE_NEQUALS  <EXPR3>

<EXPR3>     ::= <CMP_LT> | <CMP_LEQT> | <CMP_GT> | <CMP_GEQT>  | <EXPR4>
<CMP_LT>    ::= <EXPR3> TKTYPE_LT    <EXPR4>
<CMP_LEQT>  ::= <EXPR3> TKTYPE_LEQT  <EXPR4>
<CMP_GT>    ::= <EXPR3> TKTYPE_GT    <EXPR4>
<CMP_GEQT>  ::= <EXPR3> TKTYPE_GEQT  <EXPR4>

<EXPR4> ::= <DIV> | <MULT>  | <EXPR5>
<MULT>  ::= <EXPR4> TKTYPE_MULT  <EXPR5>
<DIV>   ::= <EXPR4> TKTYPE_DIV   <EXPR5>

<EXPR5> ::= <SUM> | <SUB>  | <EXPR6>
<SUM>   ::= <EXPR5> TKTYPE_SUM  <EXPR6>
<SUB>   ::= <EXPR5> TKTYPE_SUB  <EXPR6>

<EXPR6> ::= TKTYPE_VAR  | <CONST> | TKTYPE_OPPAREN <EXPR> TKTYPE_CLPAREN

<CONST> ::= TKTYPE_INT | TKTYPE_FLOAT | TKTYPE_HEXINT | TKTYPE_OCTALINT | TKTYPE_FALSE | TKTYPE_TRUE | TKTYPE_STRLIT
<TIPO>  ::= TKTYPE_T_INT | TKTYPE_T_CHAR | TKTYPE_T_BOOL | TKTYPE_T_LONG | TKTYPE_T_FLOAT | TKTYPE_T_DOUBLE
