<STMTS> ::= <STMTS> <STMT> | <STMT>
<STMT>  ::= <DEC>
<DEC>   ::= <TIPO> TKTYPE_VAR TKTYPE_ATTRIBUTION <EXPR> TKTYPE_SMCOLON

<EXPR>  ::= <EXPR>  <COND1> <EXPR1>  | <EXPR1>
<EXPR1> ::= <EXPR1> <COND2> <EXPR2>  | <EXPR2>
<EXPR2> ::= <EXPR2> <REL1>  <EXPR3>  | <EXPR3>
<EXPR3> ::= <EXPR3> <REL2>  <EXPR4>  | <EXPR4>
<EXPR4> ::= <EXPR4> <OP1>   <EXPR5>  | <EXPR5>
<EXPR5> ::= <EXPR5> <OP2>   <EXPR6>  | <EXPR6>
<EXPR6> ::= TKTYPE_VAR  | <CONST> | TKTYPE_OPPAREN <EXPR> TKTYPE_CLPAREN

<COND1>  ::= TKTYPE_LOGIC_OR
<COND2>  ::= TKTYPE_LOGIC_AND
<REL1>   ::= TKTYPE_EQUALS | TKTYPE_NEQUALS
<REL2>   ::= TKTYPE_LT   | TKTYPE_LEQT | TKTYPE_GT | TKTYPE_GEQT
<OP1>    ::= TKTYPE_SUM  | TKTYPE_SUB 
<OP2>    ::= TKTYPE_MULT | TKTYPE_DIV

<CONST> ::= TKTYPE_INT | TKTYPE_FLOAT | TKTYPE_HEXINT | TKTYPE_OCTALINT | TKTYPE_FALSE | TKTYPE_TRUE

<TIPO>  ::= TKTYPE_T_INT | TKTYPE_T_CHAR | TKTYPE_T_BOOL | TKTYPE_T_LONG | TKTYPE_T_FLOAT | TKTYPE_T_DOUBLE
