#include "../includes/grammar.h"
#include <assert.h>
long goto_table[73][VAR_NUM_VARS] = {
	[1] = { [VAR_STMTS] = 2
, [VAR_STMT] = 3
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_TIPO] = 6
, [TKTYPE_VAR] = 7
, [VAR_LOGIC_OR] = 8
, [VAR_EXPR1] = 9
, [VAR_LOGIC_AND] = 10
, [VAR_EXPR2] = 11
, [VAR_CMP_EQ] = 12
, [VAR_CMP_NEQ] = 13
, [VAR_EXPR3] = 14
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
, [TKTYPE_T_INT] = 35
, [TKTYPE_T_CHAR] = 36
, [TKTYPE_T_BOOL] = 37
, [TKTYPE_T_LONG] = 38
, [TKTYPE_T_FLOAT] = 39
, [TKTYPE_T_DOUBLE] = 40
 },
	[2] = { [VAR_STMT] = 41
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_TIPO] = 6
, [TKTYPE_VAR] = 7
, [VAR_LOGIC_OR] = 8
, [VAR_EXPR1] = 9
, [VAR_LOGIC_AND] = 10
, [VAR_EXPR2] = 11
, [VAR_CMP_EQ] = 12
, [VAR_CMP_NEQ] = 13
, [VAR_EXPR3] = 14
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
, [TKTYPE_T_INT] = 35
, [TKTYPE_T_CHAR] = 36
, [TKTYPE_T_BOOL] = 37
, [TKTYPE_T_LONG] = 38
, [TKTYPE_T_FLOAT] = 39
, [TKTYPE_T_DOUBLE] = 40
 },
	[3] = {  },
	[4] = {  },
	[5] = { [TKTYPE_SMCOLON] = 42
, [TKTYPE_LOGIC_OR] = 43
 },
	[6] = { [TKTYPE_VAR] = 44
 },
	[7] = {  },
	[8] = {  },
	[9] = { [TKTYPE_LOGIC_AND] = 45
 },
	[10] = {  },
	[11] = { [TKTYPE_EQUALS] = 46
, [TKTYPE_NEQUALS] = 47
 },
	[12] = {  },
	[13] = {  },
	[14] = { [TKTYPE_LT] = 48
, [TKTYPE_LEQT] = 49
, [TKTYPE_GT] = 50
, [TKTYPE_GEQT] = 51
 },
	[15] = {  },
	[16] = {  },
	[17] = {  },
	[18] = {  },
	[19] = { [TKTYPE_MULT] = 52
, [TKTYPE_DIV] = 53
 },
	[20] = {  },
	[21] = {  },
	[22] = { [TKTYPE_SUM] = 54
, [TKTYPE_SUB] = 55
 },
	[23] = {  },
	[24] = {  },
	[25] = {  },
	[26] = {  },
	[27] = { [VAR_EXPR] = 56
, [TKTYPE_VAR] = 7
, [VAR_LOGIC_OR] = 8
, [VAR_EXPR1] = 9
, [VAR_LOGIC_AND] = 10
, [VAR_EXPR2] = 11
, [VAR_CMP_EQ] = 12
, [VAR_CMP_NEQ] = 13
, [VAR_EXPR3] = 14
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[28] = {  },
	[29] = {  },
	[30] = {  },
	[31] = {  },
	[32] = {  },
	[33] = {  },
	[34] = {  },
	[35] = {  },
	[36] = {  },
	[37] = {  },
	[38] = {  },
	[39] = {  },
	[40] = {  },
	[41] = {  },
	[42] = {  },
	[43] = { [TKTYPE_VAR] = 7
, [VAR_EXPR1] = 57
, [VAR_LOGIC_AND] = 10
, [VAR_EXPR2] = 11
, [VAR_CMP_EQ] = 12
, [VAR_CMP_NEQ] = 13
, [VAR_EXPR3] = 14
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[44] = { [TKTYPE_ATTRIBUTION] = 58
 },
	[45] = { [TKTYPE_VAR] = 7
, [VAR_EXPR2] = 59
, [VAR_CMP_EQ] = 12
, [VAR_CMP_NEQ] = 13
, [VAR_EXPR3] = 14
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[46] = { [TKTYPE_VAR] = 7
, [VAR_EXPR3] = 60
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[47] = { [TKTYPE_VAR] = 7
, [VAR_EXPR3] = 61
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[48] = { [TKTYPE_VAR] = 7
, [VAR_EXPR4] = 62
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[49] = { [TKTYPE_VAR] = 7
, [VAR_EXPR4] = 63
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[50] = { [TKTYPE_VAR] = 7
, [VAR_EXPR4] = 64
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[51] = { [TKTYPE_VAR] = 7
, [VAR_EXPR4] = 65
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[52] = { [TKTYPE_VAR] = 7
, [VAR_EXPR5] = 66
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[53] = { [TKTYPE_VAR] = 7
, [VAR_EXPR5] = 67
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[54] = { [TKTYPE_VAR] = 7
, [VAR_EXPR6] = 68
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[55] = { [TKTYPE_VAR] = 7
, [VAR_EXPR6] = 69
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[56] = { [TKTYPE_LOGIC_OR] = 43
, [TKTYPE_CLPAREN] = 70
 },
	[57] = { [TKTYPE_LOGIC_AND] = 45
 },
	[58] = { [VAR_EXPR] = 71
, [TKTYPE_VAR] = 7
, [VAR_LOGIC_OR] = 8
, [VAR_EXPR1] = 9
, [VAR_LOGIC_AND] = 10
, [VAR_EXPR2] = 11
, [VAR_CMP_EQ] = 12
, [VAR_CMP_NEQ] = 13
, [VAR_EXPR3] = 14
, [VAR_CMP_LT] = 15
, [VAR_CMP_LEQT] = 16
, [VAR_CMP_GT] = 17
, [VAR_CMP_GEQT] = 18
, [VAR_EXPR4] = 19
, [VAR_DIV] = 20
, [VAR_MULT] = 21
, [VAR_EXPR5] = 22
, [VAR_SUM] = 23
, [VAR_SUB] = 24
, [VAR_EXPR6] = 25
, [VAR_CONST] = 26
, [TKTYPE_OPPAREN] = 27
, [TKTYPE_INT] = 28
, [TKTYPE_FLOAT] = 29
, [TKTYPE_HEXINT] = 30
, [TKTYPE_OCTALINT] = 31
, [TKTYPE_FALSE] = 32
, [TKTYPE_TRUE] = 33
, [TKTYPE_STRLIT] = 34
 },
	[59] = { [TKTYPE_EQUALS] = 46
, [TKTYPE_NEQUALS] = 47
 },
	[60] = { [TKTYPE_LT] = 48
, [TKTYPE_LEQT] = 49
, [TKTYPE_GT] = 50
, [TKTYPE_GEQT] = 51
 },
	[61] = { [TKTYPE_LT] = 48
, [TKTYPE_LEQT] = 49
, [TKTYPE_GT] = 50
, [TKTYPE_GEQT] = 51
 },
	[62] = { [TKTYPE_MULT] = 52
, [TKTYPE_DIV] = 53
 },
	[63] = { [TKTYPE_MULT] = 52
, [TKTYPE_DIV] = 53
 },
	[64] = { [TKTYPE_MULT] = 52
, [TKTYPE_DIV] = 53
 },
	[65] = { [TKTYPE_MULT] = 52
, [TKTYPE_DIV] = 53
 },
	[66] = { [TKTYPE_SUM] = 54
, [TKTYPE_SUB] = 55
 },
	[67] = { [TKTYPE_SUM] = 54
, [TKTYPE_SUB] = 55
 },
	[68] = {  },
	[69] = {  },
	[70] = {  },
	[71] = { [TKTYPE_SMCOLON] = 72
, [TKTYPE_LOGIC_OR] = 43
 },
	[72] = {  },
};

#define PROD(tgt, ...) (Production) \
                {.target = tgt, .elements = {__VA_ARGS__}, .num_elems = (sizeof((long[]){__VA_ARGS__})/sizeof(long))}
Production rdc_table[73] = {
	[3] = PROD(VAR_STMTS,   VAR_STMT),
	[4] = PROD(VAR_STMT,   VAR_DEC),
	[7] = PROD(VAR_EXPR6,   TKTYPE_VAR),
	[8] = PROD(VAR_EXPR,   VAR_LOGIC_OR),
	[9] = PROD(VAR_EXPR,   VAR_EXPR1),
	[10] = PROD(VAR_EXPR1,   VAR_LOGIC_AND),
	[11] = PROD(VAR_EXPR1,   VAR_EXPR2),
	[12] = PROD(VAR_EXPR2,   VAR_CMP_EQ),
	[13] = PROD(VAR_EXPR2,   VAR_CMP_NEQ),
	[14] = PROD(VAR_EXPR2,   VAR_EXPR3),
	[15] = PROD(VAR_EXPR3,   VAR_CMP_LT),
	[16] = PROD(VAR_EXPR3,   VAR_CMP_LEQT),
	[17] = PROD(VAR_EXPR3,   VAR_CMP_GT),
	[18] = PROD(VAR_EXPR3,   VAR_CMP_GEQT),
	[19] = PROD(VAR_EXPR3,   VAR_EXPR4),
	[20] = PROD(VAR_EXPR4,   VAR_DIV),
	[21] = PROD(VAR_EXPR4,   VAR_MULT),
	[22] = PROD(VAR_EXPR4,   VAR_EXPR5),
	[23] = PROD(VAR_EXPR5,   VAR_SUM),
	[24] = PROD(VAR_EXPR5,   VAR_SUB),
	[25] = PROD(VAR_EXPR5,   VAR_EXPR6),
	[26] = PROD(VAR_EXPR6,   VAR_CONST),
	[28] = PROD(VAR_CONST,   TKTYPE_INT),
	[29] = PROD(VAR_CONST,   TKTYPE_FLOAT),
	[30] = PROD(VAR_CONST,   TKTYPE_HEXINT),
	[31] = PROD(VAR_CONST,   TKTYPE_OCTALINT),
	[32] = PROD(VAR_CONST,   TKTYPE_FALSE),
	[33] = PROD(VAR_CONST,   TKTYPE_TRUE),
	[34] = PROD(VAR_CONST,   TKTYPE_STRLIT),
	[35] = PROD(VAR_TIPO,   TKTYPE_T_INT),
	[36] = PROD(VAR_TIPO,   TKTYPE_T_CHAR),
	[37] = PROD(VAR_TIPO,   TKTYPE_T_BOOL),
	[38] = PROD(VAR_TIPO,   TKTYPE_T_LONG),
	[39] = PROD(VAR_TIPO,   TKTYPE_T_FLOAT),
	[40] = PROD(VAR_TIPO,   TKTYPE_T_DOUBLE),
	[41] = PROD(VAR_STMTS,   VAR_STMTS, VAR_STMT),
	[42] = PROD(VAR_STMT,   VAR_EXPR, TKTYPE_SMCOLON),
	[57] = PROD(VAR_LOGIC_OR,   VAR_EXPR, TKTYPE_LOGIC_OR, VAR_EXPR1),
	[59] = PROD(VAR_LOGIC_AND,   VAR_EXPR1, TKTYPE_LOGIC_AND, VAR_EXPR2),
	[60] = PROD(VAR_CMP_EQ,   VAR_EXPR2, TKTYPE_EQUALS, VAR_EXPR3),
	[61] = PROD(VAR_CMP_NEQ,   VAR_EXPR2, TKTYPE_NEQUALS, VAR_EXPR3),
	[62] = PROD(VAR_CMP_LT,   VAR_EXPR3, TKTYPE_LT, VAR_EXPR4),
	[63] = PROD(VAR_CMP_LEQT,   VAR_EXPR3, TKTYPE_LEQT, VAR_EXPR4),
	[64] = PROD(VAR_CMP_GT,   VAR_EXPR3, TKTYPE_GT, VAR_EXPR4),
	[65] = PROD(VAR_CMP_GEQT,   VAR_EXPR3, TKTYPE_GEQT, VAR_EXPR4),
	[66] = PROD(VAR_MULT,   VAR_EXPR4, TKTYPE_MULT, VAR_EXPR5),
	[67] = PROD(VAR_DIV,   VAR_EXPR4, TKTYPE_DIV, VAR_EXPR5),
	[68] = PROD(VAR_SUM,   VAR_EXPR5, TKTYPE_SUM, VAR_EXPR6),
	[69] = PROD(VAR_SUB,   VAR_EXPR5, TKTYPE_SUB, VAR_EXPR6),
	[70] = PROD(VAR_EXPR6,   TKTYPE_OPPAREN, VAR_EXPR, TKTYPE_CLPAREN),
	[72] = PROD(VAR_DEC,   VAR_TIPO, TKTYPE_VAR, TKTYPE_ATTRIBUTION, VAR_EXPR, TKTYPE_SMCOLON),
};
char *var2str(VARTYPE t){
  switch(t){
    case VAR_STMTS: return "VAR_STMTS";
    case VAR_STMT: return "VAR_STMT";
    case VAR_DEC: return "VAR_DEC";
    case VAR_EXPR: return "VAR_EXPR";
    case VAR_LOGIC_OR: return "VAR_LOGIC_OR";
    case VAR_EXPR1: return "VAR_EXPR1";
    case VAR_LOGIC_AND: return "VAR_LOGIC_AND";
    case VAR_EXPR2: return "VAR_EXPR2";
    case VAR_CMP_EQ: return "VAR_CMP_EQ";
    case VAR_CMP_NEQ: return "VAR_CMP_NEQ";
    case VAR_EXPR3: return "VAR_EXPR3";
    case VAR_CMP_LT: return "VAR_CMP_LT";
    case VAR_CMP_LEQT: return "VAR_CMP_LEQT";
    case VAR_CMP_GT: return "VAR_CMP_GT";
    case VAR_CMP_GEQT: return "VAR_CMP_GEQT";
    case VAR_EXPR4: return "VAR_EXPR4";
    case VAR_MULT: return "VAR_MULT";
    case VAR_DIV: return "VAR_DIV";
    case VAR_EXPR5: return "VAR_EXPR5";
    case VAR_SUM: return "VAR_SUM";
    case VAR_SUB: return "VAR_SUB";
    case VAR_EXPR6: return "VAR_EXPR6";
    case VAR_CONST: return "VAR_CONST";
    case VAR_TIPO: return "VAR_TIPO";
    default: assert(0 && "type2str: invalid value");
  }
}
