#include "../includes/grammar.h"
#include <assert.h>
long goto_table[102][VAR_NUM_VARS] = {
	[1] = { [VAR_STMTS] = 2
, [VAR_STMT] = 3
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[2] = { [VAR_STMT] = 48
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[3] = {  },
	[4] = {  },
	[5] = { [TKTYPE_SMCOLON] = 49
, [TKTYPE_LOGIC_OR] = 50
 },
	[6] = {  },
	[7] = { [VAR_ELSE] = 51
, [TKTYPE_ELSE] = 52
 },
	[8] = {  },
	[9] = {  },
	[10] = { [TKTYPE_OPPAREN] = 53
 },
	[11] = { [VAR_EXPR] = 54
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[12] = { [TKTYPE_OPPAREN] = 56
 },
	[13] = { [TKTYPE_VAR] = 57
 },
	[14] = { [TKTYPE_ATTRIBUTION] = 58
 },
	[15] = {  },
	[16] = { [TKTYPE_LOGIC_AND] = 59
 },
	[17] = {  },
	[18] = { [TKTYPE_EQUALS] = 60
, [TKTYPE_NEQUALS] = 61
 },
	[19] = {  },
	[20] = {  },
	[21] = { [TKTYPE_LT] = 62
, [TKTYPE_LEQT] = 63
, [TKTYPE_GT] = 64
, [TKTYPE_GEQT] = 65
 },
	[22] = {  },
	[23] = {  },
	[24] = {  },
	[25] = {  },
	[26] = { [TKTYPE_SUM] = 66
, [TKTYPE_SUB] = 67
 },
	[27] = {  },
	[28] = {  },
	[29] = { [TKTYPE_MULT] = 68
, [TKTYPE_DIV] = 69
 },
	[30] = {  },
	[31] = {  },
	[32] = {  },
	[33] = {  },
	[34] = {  },
	[35] = {  },
	[36] = {  },
	[37] = {  },
	[38] = {  },
	[39] = {  },
	[40] = {  },
	[41] = {  },
	[42] = {  },
	[43] = {  },
	[44] = {  },
	[45] = {  },
	[46] = {  },
	[47] = {  },
	[48] = {  },
	[49] = {  },
	[50] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR1] = 70
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[51] = {  },
	[52] = { [VAR_IF] = 71
, [TKTYPE_OPBRACKET] = 72
, [TKTYPE_IF] = 12
 },
	[53] = { [VAR_EXPR] = 73
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[54] = { [TKTYPE_CLPAREN] = 74
, [TKTYPE_LOGIC_OR] = 50
 },
	[55] = {  },
	[56] = { [VAR_EXPR] = 75
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[57] = { [TKTYPE_ATTRIBUTION] = 76
 },
	[58] = { [VAR_EXPR] = 77
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[59] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR2] = 78
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[60] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR3] = 79
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[61] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR3] = 80
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[62] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR4] = 81
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[63] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR4] = 82
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[64] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR4] = 83
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[65] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR4] = 84
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[66] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR5] = 85
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[67] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR5] = 86
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[68] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR6] = 87
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[69] = { [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_EXPR6] = 88
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[70] = { [TKTYPE_LOGIC_AND] = 59
 },
	[71] = {  },
	[72] = { [VAR_STMTS] = 89
, [VAR_STMT] = 3
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[73] = { [TKTYPE_CLPAREN] = 90
, [TKTYPE_LOGIC_OR] = 50
 },
	[74] = {  },
	[75] = { [TKTYPE_CLPAREN] = 91
, [TKTYPE_LOGIC_OR] = 50
 },
	[76] = { [VAR_EXPR] = 92
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_VAR] = 55
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
 },
	[77] = { [TKTYPE_SMCOLON] = 93
, [TKTYPE_LOGIC_OR] = 50
 },
	[78] = { [TKTYPE_EQUALS] = 60
, [TKTYPE_NEQUALS] = 61
 },
	[79] = { [TKTYPE_LT] = 62
, [TKTYPE_LEQT] = 63
, [TKTYPE_GT] = 64
, [TKTYPE_GEQT] = 65
 },
	[80] = { [TKTYPE_LT] = 62
, [TKTYPE_LEQT] = 63
, [TKTYPE_GT] = 64
, [TKTYPE_GEQT] = 65
 },
	[81] = { [TKTYPE_SUM] = 66
, [TKTYPE_SUB] = 67
 },
	[82] = { [TKTYPE_SUM] = 66
, [TKTYPE_SUB] = 67
 },
	[83] = { [TKTYPE_SUM] = 66
, [TKTYPE_SUB] = 67
 },
	[84] = { [TKTYPE_SUM] = 66
, [TKTYPE_SUB] = 67
 },
	[85] = { [TKTYPE_MULT] = 68
, [TKTYPE_DIV] = 69
 },
	[86] = { [TKTYPE_MULT] = 68
, [TKTYPE_DIV] = 69
 },
	[87] = {  },
	[88] = {  },
	[89] = { [VAR_STMT] = 48
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_CLBRACKET] = 94
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[90] = { [TKTYPE_OPBRACKET] = 95
 },
	[91] = { [TKTYPE_OPBRACKET] = 96
 },
	[92] = { [TKTYPE_SMCOLON] = 97
, [TKTYPE_LOGIC_OR] = 50
 },
	[93] = {  },
	[94] = {  },
	[95] = { [VAR_STMTS] = 98
, [VAR_STMT] = 3
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[96] = { [VAR_STMTS] = 99
, [VAR_STMT] = 3
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[97] = {  },
	[98] = { [VAR_STMT] = 48
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_CLBRACKET] = 100
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[99] = { [VAR_STMT] = 48
, [VAR_DEC] = 4
, [VAR_EXPR] = 5
, [VAR_ASSIGN] = 6
, [VAR_IF] = 7
, [VAR_IF_ELSE] = 8
, [VAR_WHILE] = 9
, [TKTYPE_WHILE] = 10
, [TKTYPE_OPPAREN] = 11
, [TKTYPE_CLBRACKET] = 101
, [TKTYPE_IF] = 12
, [VAR_TIPO] = 13
, [TKTYPE_VAR] = 14
, [VAR_LOG_OR] = 15
, [VAR_EXPR1] = 16
, [VAR_LOG_AND] = 17
, [VAR_EXPR2] = 18
, [VAR_CMP_EQ] = 19
, [VAR_CMP_NEQ] = 20
, [VAR_EXPR3] = 21
, [VAR_CMP_LT] = 22
, [VAR_CMP_LEQT] = 23
, [VAR_CMP_GT] = 24
, [VAR_CMP_GEQT] = 25
, [VAR_EXPR4] = 26
, [VAR_SUM] = 27
, [VAR_SUB] = 28
, [VAR_EXPR5] = 29
, [VAR_MULT] = 30
, [VAR_DIV] = 31
, [VAR_EXPR6] = 32
, [VAR_CONST] = 33
, [VAR_PAREN_EXPR] = 34
, [TKTYPE_INT] = 35
, [TKTYPE_FLOAT] = 36
, [TKTYPE_HEXINT] = 37
, [TKTYPE_OCTALINT] = 38
, [TKTYPE_FALSE] = 39
, [TKTYPE_TRUE] = 40
, [TKTYPE_STRLIT] = 41
, [TKTYPE_T_INT] = 42
, [TKTYPE_T_CHAR] = 43
, [TKTYPE_T_BOOL] = 44
, [TKTYPE_T_LONG] = 45
, [TKTYPE_T_FLOAT] = 46
, [TKTYPE_T_DOUBLE] = 47
 },
	[100] = {  },
	[101] = {  },
};

#define PROD(tgt, ...) (Production) \
                {.target = tgt, .elements = {__VA_ARGS__}, .num_elems = (sizeof((long[]){__VA_ARGS__})/sizeof(long))}
Production rdc_table[102] = {
	[3] = PROD(VAR_STMTS,   VAR_STMT),
	[4] = PROD(VAR_STMT,   VAR_DEC),
	[6] = PROD(VAR_STMT,   VAR_ASSIGN),
	[7] = PROD(VAR_STMT,   VAR_IF),
	[8] = PROD(VAR_STMT,   VAR_IF_ELSE),
	[9] = PROD(VAR_STMT,   VAR_WHILE),
	[15] = PROD(VAR_EXPR,   VAR_LOG_OR),
	[16] = PROD(VAR_EXPR,   VAR_EXPR1),
	[17] = PROD(VAR_EXPR1,   VAR_LOG_AND),
	[18] = PROD(VAR_EXPR1,   VAR_EXPR2),
	[19] = PROD(VAR_EXPR2,   VAR_CMP_EQ),
	[20] = PROD(VAR_EXPR2,   VAR_CMP_NEQ),
	[21] = PROD(VAR_EXPR2,   VAR_EXPR3),
	[22] = PROD(VAR_EXPR3,   VAR_CMP_LT),
	[23] = PROD(VAR_EXPR3,   VAR_CMP_LEQT),
	[24] = PROD(VAR_EXPR3,   VAR_CMP_GT),
	[25] = PROD(VAR_EXPR3,   VAR_CMP_GEQT),
	[26] = PROD(VAR_EXPR3,   VAR_EXPR4),
	[27] = PROD(VAR_EXPR4,   VAR_SUM),
	[28] = PROD(VAR_EXPR4,   VAR_SUB),
	[29] = PROD(VAR_EXPR4,   VAR_EXPR5),
	[30] = PROD(VAR_EXPR5,   VAR_MULT),
	[31] = PROD(VAR_EXPR5,   VAR_DIV),
	[32] = PROD(VAR_EXPR5,   VAR_EXPR6),
	[33] = PROD(VAR_EXPR6,   VAR_CONST),
	[34] = PROD(VAR_EXPR6,   VAR_PAREN_EXPR),
	[35] = PROD(VAR_CONST,   TKTYPE_INT),
	[36] = PROD(VAR_CONST,   TKTYPE_FLOAT),
	[37] = PROD(VAR_CONST,   TKTYPE_HEXINT),
	[38] = PROD(VAR_CONST,   TKTYPE_OCTALINT),
	[39] = PROD(VAR_CONST,   TKTYPE_FALSE),
	[40] = PROD(VAR_CONST,   TKTYPE_TRUE),
	[41] = PROD(VAR_CONST,   TKTYPE_STRLIT),
	[42] = PROD(VAR_TIPO,   TKTYPE_T_INT),
	[43] = PROD(VAR_TIPO,   TKTYPE_T_CHAR),
	[44] = PROD(VAR_TIPO,   TKTYPE_T_BOOL),
	[45] = PROD(VAR_TIPO,   TKTYPE_T_LONG),
	[46] = PROD(VAR_TIPO,   TKTYPE_T_FLOAT),
	[47] = PROD(VAR_TIPO,   TKTYPE_T_DOUBLE),
	[48] = PROD(VAR_STMTS,   VAR_STMTS, VAR_STMT),
	[49] = PROD(VAR_STMT,   VAR_EXPR, TKTYPE_SMCOLON),
	[51] = PROD(VAR_IF_ELSE,   VAR_IF, VAR_ELSE),
	[55] = PROD(VAR_EXPR6,   TKTYPE_VAR),
	[70] = PROD(VAR_LOG_OR,   VAR_EXPR, TKTYPE_LOGIC_OR, VAR_EXPR1),
	[71] = PROD(VAR_ELSE,   TKTYPE_ELSE, VAR_IF),
	[74] = PROD(VAR_PAREN_EXPR,   TKTYPE_OPPAREN, VAR_EXPR, TKTYPE_CLPAREN),
	[78] = PROD(VAR_LOG_AND,   VAR_EXPR1, TKTYPE_LOGIC_AND, VAR_EXPR2),
	[79] = PROD(VAR_CMP_EQ,   VAR_EXPR2, TKTYPE_EQUALS, VAR_EXPR3),
	[80] = PROD(VAR_CMP_NEQ,   VAR_EXPR2, TKTYPE_NEQUALS, VAR_EXPR3),
	[81] = PROD(VAR_CMP_LT,   VAR_EXPR3, TKTYPE_LT, VAR_EXPR4),
	[82] = PROD(VAR_CMP_LEQT,   VAR_EXPR3, TKTYPE_LEQT, VAR_EXPR4),
	[83] = PROD(VAR_CMP_GT,   VAR_EXPR3, TKTYPE_GT, VAR_EXPR4),
	[84] = PROD(VAR_CMP_GEQT,   VAR_EXPR3, TKTYPE_GEQT, VAR_EXPR4),
	[85] = PROD(VAR_SUM,   VAR_EXPR4, TKTYPE_SUM, VAR_EXPR5),
	[86] = PROD(VAR_SUB,   VAR_EXPR4, TKTYPE_SUB, VAR_EXPR5),
	[87] = PROD(VAR_MULT,   VAR_EXPR5, TKTYPE_MULT, VAR_EXPR6),
	[88] = PROD(VAR_DIV,   VAR_EXPR5, TKTYPE_DIV, VAR_EXPR6),
	[93] = PROD(VAR_ASSIGN,   TKTYPE_VAR, TKTYPE_ATTRIBUTION, VAR_EXPR, TKTYPE_SMCOLON),
	[94] = PROD(VAR_ELSE,   TKTYPE_ELSE, TKTYPE_OPBRACKET, VAR_STMTS, TKTYPE_CLBRACKET),
	[97] = PROD(VAR_DEC,   VAR_TIPO, TKTYPE_VAR, TKTYPE_ATTRIBUTION, VAR_EXPR, TKTYPE_SMCOLON),
	[100] = PROD(VAR_WHILE,   TKTYPE_WHILE, TKTYPE_OPPAREN, VAR_EXPR, TKTYPE_CLPAREN, TKTYPE_OPBRACKET, VAR_STMTS, TKTYPE_CLBRACKET),
	[101] = PROD(VAR_IF,   TKTYPE_IF, TKTYPE_OPPAREN, VAR_EXPR, TKTYPE_CLPAREN, TKTYPE_OPBRACKET, VAR_STMTS, TKTYPE_CLBRACKET),
};
char *var2str(VARTYPE t){
  switch(t){
    case VAR_STMTS: return "VAR_STMTS";
    case VAR_STMT: return "VAR_STMT";
    case VAR_WHILE: return "VAR_WHILE";
    case VAR_IF: return "VAR_IF";
    case VAR_IF_ELSE: return "VAR_IF_ELSE";
    case VAR_ELSE: return "VAR_ELSE";
    case VAR_DEC: return "VAR_DEC";
    case VAR_ASSIGN: return "VAR_ASSIGN";
    case VAR_EXPR: return "VAR_EXPR";
    case VAR_LOG_OR: return "VAR_LOG_OR";
    case VAR_EXPR1: return "VAR_EXPR1";
    case VAR_LOG_AND: return "VAR_LOG_AND";
    case VAR_EXPR2: return "VAR_EXPR2";
    case VAR_CMP_EQ: return "VAR_CMP_EQ";
    case VAR_CMP_NEQ: return "VAR_CMP_NEQ";
    case VAR_EXPR3: return "VAR_EXPR3";
    case VAR_CMP_LT: return "VAR_CMP_LT";
    case VAR_CMP_LEQT: return "VAR_CMP_LEQT";
    case VAR_CMP_GT: return "VAR_CMP_GT";
    case VAR_CMP_GEQT: return "VAR_CMP_GEQT";
    case VAR_EXPR4: return "VAR_EXPR4";
    case VAR_SUM: return "VAR_SUM";
    case VAR_SUB: return "VAR_SUB";
    case VAR_EXPR5: return "VAR_EXPR5";
    case VAR_MULT: return "VAR_MULT";
    case VAR_DIV: return "VAR_DIV";
    case VAR_EXPR6: return "VAR_EXPR6";
    case VAR_PAREN_EXPR: return "VAR_PAREN_EXPR";
    case VAR_CONST: return "VAR_CONST";
    case VAR_TIPO: return "VAR_TIPO";
    default: assert(0 && "type2str: invalid value");
  }
}
